/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2021-12-06 00:04:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1638740752458L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1638740752083L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>MIE350 Sample Web App - About</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Date Picker Javascript -->\r\n");
      out.write("<!-- https://jqueryui.com/datepicker/ -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mystyle.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"index.jsp\">MIE350 Team 8 Web App</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"about.jsp\">About the Team</a></li>\r\n");
      out.write("\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\thref=\"/mie350webapp/StudentController?action=listStudent\">Student\r\n");
      out.write("\t\t\t\t\t\tList (Public)</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"searchStudent.jsp\">Search A Student</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a data-toggle=\"dropdown\"\r\n");
      out.write("\t\t\t\t\thref=\"helpful_links.jsp\">Other Links<b class=\"caret\"></b></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"sample_html.jsp\">Sample HTML Tags</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"helpful_links.jsp\">Other Helpful Links</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.w3schools.com/html/default.asp\">HTML\r\n");
      out.write("\t\t\t\t\t\t\t\tTutorial</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.w3schools.com/bootstrap/\">BootStrap\r\n");
      out.write("\t\t\t\t\t\t\t\tCSS Tutorial</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- The following code can be added to include a Login button to the right-hand side of the navbar-->\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li><a href=\"login.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid text-center\">\r\n");
      out.write("\t\t<div class=\"row content\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-2 sidenav\">\r\n");
      out.write("\t\t\t\t<!-- You can put left sidebar links here if you want to. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-8 text-left\">\r\n");
      out.write("\t\t\t\t<h1>About Team 8</h1>\r\n");
      out.write("\t\t\t\tThis team consists of six Third-Year Industrial Engineering (Indy) students, \r\n");
      out.write("\t\t\t\tstudying at the <a href=\"http://www.utoronto.ca\">University of Toronto</a>. We are\r\n");
      out.write("\t\t\t\tdeveloping this web application for our <b>MIE350: Design & Analysis of Information \r\n");
      out.write("\t\t\t\tSystems</b> course.<br>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<h2>Meet the Team Members</h2>\r\n");
      out.write("\t\t\t\t<br>Read below for a quick message from each of our team members to get to know \r\n");
      out.write("\t\t\t\tthem a bit better!<br>\r\n");
      out.write("\t\t\t\t<h3>Gabriel Escobar</h3>\r\n");
      out.write("\t\t\t\t<p>Hi! My name is Gabriel, and I'm an Industrial Engineering student at UofT who is very \r\n");
      out.write("\t\t\t\tinterested in music and reading. Since starting University, I've become extremely interested \r\n");
      out.write("\t\t\t\tin Computer Science and have engaged in topics such as AI, web development, and video game \r\n");
      out.write("\t\t\t\tdevelopment. As such, I've gotten the chance to learn Python, Java, SQL, HTML, CSS, JavaScript, \r\n");
      out.write("\t\t\t\tand R. I love living in a big city like Toronto and am excited about working with this team to \r\n");
      out.write("\t\t\t\tcreate a web application that helps students find the best restaurants in the area.</p>\r\n");
      out.write("\t\t\t\t<h3>Santiago Gomez Montenegro</h3>\r\n");
      out.write("\t\t\t\t<p>I am a third-year student at the University of Toronto pursuing a Bachelor of Applied Science \r\n");
      out.write("\t\t\t\tin Industrial Engineering. Software development and artificial intelligence are my top academic \r\n");
      out.write("\t\t\t\tinterests, and my program has provided me with the flexibility to explore them. This summer I got \r\n");
      out.write("\t\t\t\tthe opportunity to work at Microsoft where I developed  a code coverage tool to assist Office \r\n");
      out.write("\t\t\t\tengineers in evaluating source code changes. I am hoping to bring some of my web development \r\n");
      out.write("\t\t\t\texperience from the internship to this project.</p>\r\n");
      out.write("\t\t\t\t<h3>Alexandra Hon</h3>\r\n");
      out.write("\t\t\t\t<p>Hey! I'm Alex and like the rest of my group members, I'm an Industrial Engineering student at \r\n");
      out.write("\t\t\t\tthe University of Toronto. Over the past few years I've been able to develop my skills in Python, \r\n");
      out.write("\t\t\t\tJava, SQL and R. I love trying new restaurants and food stalls around Toronto so I'm excited to \r\n");
      out.write("\t\t\t\twork with this team to develop a website to help students explore the city through food!</p>\r\n");
      out.write("\t\t\t\t<h3>Arieana Hussain</h3>\r\n");
      out.write("\t\t\t\t<p>Hello! My name is Arieana and I am a third year Industrial Engineering student at the University \r\n");
      out.write("\t\t\t\tof Toronto. Some of my hobbies include photography, reading, and cooking. I have been working on \r\n");
      out.write("\t\t\t\tdeveloping my technical skills by learning Python, Java, SQL and R. I am looking forward to applying \r\n");
      out.write("\t\t\t\tmy skills to this website and providing university students with the opportunity to discover restaurants \r\n");
      out.write("\t\t\t\taround Toronto.</p>\r\n");
      out.write("\t\t\t\t<h3>Maia Kanceljak</h3>\r\n");
      out.write("\t\t\t\t<p>Hello hello! I'm Maia and I started out in Materials Science Engineering (MSE) in first year \r\n");
      out.write("\t\t\t\tbefore switching over to Indy. I like reading, doing sudoku puzzles, playing soccer, skiing, \r\n");
      out.write("\t\t\t\tand swimming. I worked with Big Data at Geotab this past summer and I got pretty good at Python, \r\n");
      out.write("\t\t\t\tSQL and writing documentation, so I'm excited to apply all that to this project!</p>\r\n");
      out.write("\t\t\t\t<h3>Jose Pablo Siliezar Carrillo</h3>\r\n");
      out.write("\t\t\t\t<p>Hello there! My name is Jose, and I'm an Industrial Engineering (Indy) student. Some of my \r\n");
      out.write("\t\t\t\thobbies are exercising, listening to music and playing instruments! In the last few years, I've \r\n");
      out.write("\t\t\t\tlearned Python, Java, SQL and a bit of R. I am looking forward to learning about project \r\n");
      out.write("\t\t\t\tmanagement and website design (and the programming languages used in it).</p>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<h2>Look at our lovely campus!</h2>\r\n");
      out.write("\t\t\t\t<img src=\"img/campus.jpg\"> <br />\r\n");
      out.write("\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-2 sidenav\">\r\n");
      out.write("\t\t\t\t<!-- You can put right sidebar links here if you want to. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("<footer class=\"container-fluid text-center\">\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\tThis is the server prototype for Team 8's web application. <br>\r\n");
      out.write("\t\tMIE350 Team 8 Web Application &#169;\r\n");
      out.write("\t\t");
      out.print(new java.text.SimpleDateFormat("yyyy")
					.format(new java.util.Date()));
      out.write("\r\n");
      out.write("\t\tUniversity of Toronto <br /> Bootstrap Theme &#169; <a\r\n");
      out.write("\t\t\thref=\"http://getbootstrap.com/\">Bootstrap</a><br /> JavaScript for\r\n");
      out.write("\t\tTable Sorting &#169; <a\r\n");
      out.write("\t\t\thref=\"https://kryogenix.org/code/browser/sorttable/\">Stuart\r\n");
      out.write("\t\t\tLangridge</a><br />\r\n");
      out.write("\t\t\tJavaScript for Date Picker &#169; <a href=\"https://jqueryui.com/datepicker/\">https://jqueryui.com/datepicker/</a>\r\n");
      out.write("\t</p>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
